const express=require('express');
const router=express.Router();
const {signup, login, logout}=require('../controllers/auth.js');
const { changePassword } = require('../controllers/auth.js');
const {userAuth}=require('../middlewares/auth');
router.post('/signup',signup);
router.post('/login',login);
router.post('/logout',logout);
router.post('/change-password', userAuth, changePassword);
module.exports=router;
